"""add a bio and profile pic

Revision ID: 274393c6600f
Revises: a2bcc21d2ab5
Create Date: 2021-04-22 15:48:58.951748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '274393c6600f'
down_revision = 'a2bcc21d2ab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
